apiVersion: apps/v1  # API版本
kind: Deployment  # API对象类型
metadata:
  name: go-rpc-simple
  labels:
    app: go-rpc-simple
spec:
  selector:
    matchLabels:
      app: go-rpc-simple
  replicas: 2  # Pod 副本数量
  template:  # Pod 模板
    metadata:
      labels:
        app: go-rpc-simple
    spec:
      containers:
        - name: go-rpc-simple
          image: qxybest/go-rpc-simple:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9001
          # env:
          # - name: REDIS_URL
          #   value: redis.default.svc.cluster.local:6379
---
apiVersion: v1
kind: Service
metadata:
  name: go-rpc-simple-service
  labels:
    app: go-rpc-simple
spec:
  selector:
    app: go-rpc-simple
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 9001
